/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tedkwan_javafem_jni_DuffingOscil */

#ifndef _Included_net_tedkwan_javafem_jni_DuffingOscil
#define _Included_net_tedkwan_javafem_jni_DuffingOscil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_tedkwan_javafem_jni_DuffingOscil
 * Method:    rk4
 * Signature: ([D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_tedkwan_javafem_jni_DuffingOscil_rk4
  (JNIEnv *, jobject, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
