/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class net_tedkwan_javafemjni_TwoDimPhase */

#ifndef _Included_net_tedkwan_javafemjni_TwoDimPhase
#define _Included_net_tedkwan_javafemjni_TwoDimPhase
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     net_tedkwan_javafemjni_TwoDimPhase
 * Method:    rk4
 * Signature: ([DLjava/lang/String;)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_net_tedkwan_javafemjni_TwoDimPhase_rk4
  (JNIEnv *, jobject, jdoubleArray, jstring);

#ifdef __cplusplus
}
#endif
#endif
